#!/bin/bash

## Author: Kasin Sparks
## Date: 14 DEC 2019
## Objective: A program to fetch and output the GPU temp

maxWarningTemp=90
middleWarningTemp=70

#command nvidia-smi -q -d TEMPERATURE | grep 'GPU Current Temp' | cut -d ':' -f 2 | cut -d ' ' -f 2 | cat >> ~/.scripts/gpu_temp
curTemp=$(nvidia-smi -q -d TEMPERATURE | grep 'GPU Current Temp' | cut -d ':' -f 2 | cut -d ' ' -f 2)

echo ${curTemp}°C
echo

if [[ $curTemp -gt $maxWarningTemp ]]; then
	echo \#FF0000	
elif [[ $curTemp -gt $middleWarningTemp ]]; then
	echo \#FFFF00
else
	echo \#00FF00
fi
